version: 2
jobs:
  build:
    docker:
      - image: futtetennista/hakyll:4.12.5.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b1:c3:67:a4:f1:c2:0e:28:34:3a:fd:fe:d1:68:38:cc"
      - checkout
      - restore_cache:
          keys:
            - v1-stack-work-{{ checksum "site.cabal" }}
      - run:
          name: Build the static site generator executable
          command: stack build
      - save_cache:
          key: v1-stack-work-{{ checksum "site.cabal" }}
          paths:
            - ~/website-hakyll/.stack-work
            - /root/.stack
      - run:
          name: Build the site
          command: stack exec site rebuild
      - store_artifacts:
          path: _site
          destination: built_site
      - deploy:
          name: Deploy to Github Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              .circleci/deploy.sh
            fi
