name: Publish the site to Github Pages (ajdawson.github.io)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Build static site generator
        run: stack build

      - name: Build the static site
        run: stack exec site rebuild

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: ajdawson/ajdawson.github.io
          publish_branch: master
          publish_dir: ./_site
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
